### ISSUE TITLE
Will there be a version for linux?

### ISSUE THREAD

**Issue by NotFrants** [JustRedTTG/moss-desktop#1]

**Comment by JustRedTTG** [comment]
it is in testing, current test build works but requires sudo to install

**Comment by NotFrants** [comment]
Awesome! I have nothing against sudo install, so that seems fine.

**Comment by JustRedTTG** [comment]
Then here's a test build (tested on kali, failed without sudo, if it works without sudo for you, please do tell): https://filebin.net/0yx9xycq88xeyvyu

**Comment by NotFrants** [comment]
Ok thanks!

**Comment by JustRedTTG** [comment]
@NotFrants Could you confirm if this causes a segmentation fault for you after installing and pressing launch? https://filebin.net/hdunh63b5tfa9y6g

**Comment by JustRedTTG** [comment]
nvm appears to be an issue with nuitka again, on linux this time, only after install
