### ISSUE TITLE
If the app is forcfully fullscreened, the text/progress is not centered

### ISSUE THREAD

**Issue by NotFrants** [JustRedTTG/moss-desktop#6]
Here is a video
https://github.com/user-attachments/assets/820db0d0-0036-45ba-b791-9c06d89142f0

I can forcefully fullscreen the app using Mod+F on hyprland (WM).
I'm sure most users wont be able to do that, so it it not severe at all, but still is a nice thing to know.

**Comment by JustRedTTG** [comment]
Resizing support is actively being worked on in the improve-menu branch. But thank you for bringing the loader screen to my attention!

**Comment by JustRedTTG** [comment]
Fixed as of this commit: https://github.com/JustRedTTG/moss-desktop/commit/026661bd6aa2e14e9ff640e763af136172586d7b
