### ISSUE TITLE
unknown Format epub

### ISSUE THREAD

**Issue by feuermandel** [JustRedTTG/moss-desktop#8]
When starting MOSS on Linux, syncing lasts "forever" and epubs files are not supported at this time:

─$ pip3 install -r requirements.txt      
Requirement already satisfied: colorama==0.4.6 in ./lib/python3.12/site-packages (from -r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: pillow==10.4.0 in ./lib/python3.12/site-packages (from -r requirements.txt (line 2)) (10.4.0)
Requirement already satisfied: pygameextra==2.0.0a82 in ./lib/python3.12/site-packages (from -r requirements.txt (line 3)) (2.0.0a82)
Requirement already satisfied: PyJWT==2.9.0 in ./lib/python3.12/site-packages (from -r requirements.txt (line 4)) (2.9.0)
Requirement already satisfied: pyperclip==1.9.0 in ./lib/python3.12/site-packages (from -r requirements.txt (line 5)) (1.9.0)
Requirement already satisfied: python-box==7.2.0 in ./lib/python3.12/site-packages (from -r requirements.txt (line 6)) (7.2.0)
Requirement already satisfied: requests==2.32.3 in ./lib/python3.12/site-packages (from -r requirements.txt (line 7)) (2.32.3)
Requirement already satisfied: websocket-client==1.8.0 in ./lib/python3.12/site-packages (from -r requirements.txt (line 8)) (1.8.0)
Requirement already satisfied: appdirs==1.4.4 in ./lib/python3.12/site-packages (from -r requirements.txt (line 9)) (1.4.4)
Requirement already satisfied: pygame-ce in ./lib/python3.12/site-packages (from pygameextra==2.0.0a82->-r requirements.txt (line 3)) (2.5.2)
Requirement already satisfied: numpy in ./lib/python3.12/site-packages (from pygameextra==2.0.0a82->-r requirements.txt (line 3)) (2.1.3)
Requirement already satisfied: frozendict in ./lib/python3.12/site-packages (from pygameextra==2.0.0a82->-r requirements.txt (line 3)) (2.4.6)
Requirement already satisfied: deprecation in ./lib/python3.12/site-packages (from pygameextra==2.0.0a82->-r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.12/site-packages (from requests==2.32.3->-r requirements.txt (line 7)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.12/site-packages (from requests==2.32.3->-r requirements.txt (line 7)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.12/site-packages (from requests==2.32.3->-r requirements.txt (line 7)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.12/site-packages (from requests==2.32.3->-r requirements.txt (line 7)) (2024.8.30)
Requirement already satisfied: packaging in ./lib/python3.12/site-packages (from deprecation->pygameextra==2.0.0a82->-r requirements.txt (line 3)) (24.2)

─$ pip3 install -r requirements-Linux.txt
Requirement already satisfied: CEF4pygame==0.0 in ./lib/python3.12/site-packages (from -r requirements-Linux.txt (line 1)) (0.0)
Requirement already satisfied: cefpython3==66.0 in ./lib/python3.12/site-packages (from -r requirements-Linux.txt (line 2)) (66.0)

Config file created. You can edit it manually if you want.
Cef is not installed or is not compatible with your python version.
Unknown file type: epub
Exception in thread Thread-3 (get_documents):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/reimers/tools/moss-desktop/gui/screens/loader.py", line 107, in get_documents
    self.api.get_documents(progress)
  File "/home/reimers/tools/moss-desktop/rm_api/__init__.py", line 90, in get_documents
    get_documents_new_sync(self, progress)
  File "/home/reimers/tools/moss-desktop/rm_api/storage/new_sync.py", line 21, in get_documents_new_sync
    return get_documents_using_root(api, progress, root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reimers/tools/moss-desktop/rm_api/storage/v3.py", line 127, in get_documents_using_root
    [models.Tag(tag) for tag in content['tags']],
                                ~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
ef is not installed or is not compatible with your python version.
Unknown file type: epub
^[[B^[[B^[[Bonfig file created. You can edit it manually if you want.
Cef is not installed or is not compatible with your python version.
Unknown file type: epub
Exception in thread Thread-3 (get_documents):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/reimers/tools/moss-desktop/gui/screens/loader.py", line 107, in get_documents
    self.api.get_documents(progress)
  File "/home/reimers/tools/moss-desktop/rm_api/__init__.py", line 90, in get_documents
    get_documents_new_sync(self, progress)
  File "/home/reimers/tools/moss-desktop/rm_api/storage/new_sync.py", line 21, in get_documents_new_sync
    return get_documents_using_root(api, progress, root)

**Comment by JustRedTTG** [comment]
I recommend using experimental for the latest fixes when making issues, please check how it works on that branch and comment again. Also note that initial sync takes time depending on how many documents you have, you can disable "wait_for_everything_to_load" in config to get to the main menu before the sync is complete, you'll get the number of artifacts that need to be processed and progress at the bottom right
