### ISSUE TITLE
Could not install app

### ISSUE THREAD

**Issue by Hectofer** [JustRedTTG/moss-desktop#9]
**I got an error**
When I run *moss.exe* I get a *sync* folder that is empty, a *config.json* file and a *error.log* file which contains the following:

[*time*] Traceback (most recent call last):
  File "...\AppData\Local\Temp\ONEFIL 1\moss.py", line 3, in <module>
  File "...\AppData\Local\Temp\ONEFIL 1\gui\__main__.py", line 6, in run_gui
  File "...\AppData\Local\Temp\ONEFIL 1\gui\gui.py", line 166, in __init__
  File "...\AppData\Local\Temp\ONEFIL 1\pygameextra\display.py", line 40, in set_icon
  File "...\AppData\Local\Temp\ONEFIL 1\pygameextra\modified.py", line 167, in get_surface_file
pygame.error: Failed loading libpng16-16.dll: The specified module could not be found.

I checked, but I do have those files installed (unless I missed something

**Screenshots**
![image](https://github.com/user-attachments/assets/03098652-4895-4780-b3be-075429efb950)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version 24H2 (0S Build 26100.2454)
 - Architecture: x64-based PC
 - Python version: 3.13

**Comment by JokerZB** [comment]
Same issue here

**Comment by JustRedTTG** [comment]
> Same issue here

What's your windows version?

**Comment by JokerZB** [comment]
> > Same issue here
> 
> What's your windows version?

OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631

**Comment by JokerZB** [comment]
> Can you check if this build works for you? https://github.com/JustRedTTG/moss-desktop-action-testing/actions/runs/12231012538/artifacts/2292302127

This build installs

**Comment by JustRedTTG** [comment]
> > Can you check if this build works for you? https://github.com/JustRedTTG/moss-desktop-action-testing/actions/runs/12231012538/artifacts/2292302127
> 
> This seems to be working, but when closing a file I get the following error in the cmd (still works though):
> ```
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002157F01C4C0>
> Traceback (most recent call last):
>   File "C:\PROGRA~3\RedTTG\Moss\asyncio\proactor_events.py", line 116, in __del__
>   File "C:\PROGRA~3\RedTTG\Moss\asyncio\proactor_events.py", line 108, in close
>   File "C:\PROGRA~3\RedTTG\Moss\asyncio\base_events.py", line 751, in call_soon
>   File "C:\PROGRA~3\RedTTG\Moss\asyncio\base_events.py", line 515, in _check_closed
> RuntimeError: Event loop is closed
> ```
> 
> Also I cannot select a file (to export it for example) and I cannot open an epub.
> 
> and I get this error in cmd when I launch the app:
> ```
> PyMuPDF is not installed or is not compatible with your python version.
> Unknown file type: epub
> ```

Epub and export are not yet supported, I select features to add by poll on discord. 
The event loop error can be dismissed. 
Pymupdf has been disabled due to issues with nuitka and therefore it cannot be used for pdf rendering and previews. 
It seems the libpng issue is resolved and I will push it as a hot fix tomorrow

**Comment by JustRedTTG** [comment]
The issue with PyMuPDF has been temporally resolved by making a manual build
I have also included the patch for this issue and `libpng16-16.dll`
https://github.com/JustRedTTG/moss-desktop/releases/tag/beta-0.0.3-hotfix
